{"cells":[{"cell_type":"markdown","metadata":{"id":"fLWkiKzx9fTm"},"source":["# Excepciones\n","\n","En Python, los errores de ejecución de código se denominan excepciones. Dichas excepciones, por supuesto, son clases derivadas de una clase de excepción original, `Exception`. Sus variantes incluyen, entre otras:\n","\n","* `ZeroDivisionError`: generada por la división entre `0`.\n","* `IndexError`: generada por intentos de acceso a índices sobre la longitud total de una estructura secuencial.\n","* `NameError`: generada por la llamada a una clase, función o variable no definida previamente. "]},{"cell_type":"markdown","metadata":{"id":"qzhCjBRBzRDa"},"source":["## Traceback\n","\n","El _traceback_ es el registro de llamadas que indica exactamente dónde tiene lugar una excepción determinada. Es importante saber leer adecuadamente el _traceback_ para poder determinar el error verdadero surgido en el código.\n","\n"]},{"cell_type":"markdown","metadata":{"id":"-DKcF6q50gAp"},"source":["## Manejo de excepciones\n","\n","El manejo de excepciones hace referencia a la técnica empleada para gestionar posibles excepciones en el código y corregirlas, _debuggearlas_, silenciarlas, etc.\n","\n","La estructura en Python consiste, cómo no, en una serie de bloques indentados encabezados por las palabras reservadas `try`, `except`, `else` y `finally`."]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# Without exception catch:\n","\n","def divide(value_1, value_2):\n","    return value_1 / value_2\n","\n","\n","print(divide(4, 2), end=\"\\n\\n\")\n","print(divide(2, 0))"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# With exception catch:\n","\n","def divide(value_1, value_2):\n","    output = None\n","    \n","    try:\n","        output = value_1 / value_2\n","    except ZeroDivisionError:\n","        print(\"Warning: The second value cannot be zero.\")\n","\n","    return output\n","\n","\n","print(divide(4, 2), end=\"\\n\\n\")\n","print(divide(2, 0))"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# Exception catch with else statement:\n","\n","def divide(value_1, value_2):\n","    output = None\n","\n","    try:\n","        output = value_1 / value_2\n","    except ZeroDivisionError:\n","        print(\"Warning: The second value cannot be zero.\")\n","    else:\n","        print(\"The calculation was OK.\")\n","\n","    return output\n","\n","\n","print(divide(4, 2), end=\"\\n\\n\")\n","print(divide(2, 0))"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["# Exception catch with else statement:\n","\n","def divide(value_1, value_2):\n","    output = None\n","    \n","    try:\n","        output = value_1 / value_2\n","    except ZeroDivisionError:\n","        print(\"Warning: The second value cannot be zero.\")\n","    else:\n","        print(\"The calculation was OK.\")\n","    finally:\n","        print(\"Finished calculation process.\")\n","\n","    return output\n","\n","\n","print(divide(4, 2), end=\"\\n\\n\")\n","print(divide(2, 0))"]},{"cell_type":"markdown","metadata":{"id":"pgjDQlN605j5"},"source":["### _Ejercicio: Manejo de excepciones_\n","\n","Busca información acerca de cómo se denomina una excepción relacionada con un tipo de datos incorrecto en Python. A continuación, busca como elevar excepciones y sigue los pasos descritos en esta lista:\n","\n","1. Crea una función llamada `sum_even_values` que acepte únicamente dos argumentos posicionales.\n","2. Crea una estructura de manejo de excepciones que detecte si alguno de los argumentos no es de tipo `int` (tipo de datos incorrecto) y que, en ese caso, imprima en pantalla un aviso y devuelva el valor `0`.\n","3. La estructura del punto 2 deberá imprimir `OK.` en pantalla si no ha habido excepciones, y finalmente deberá imprimir también la frase `Finished computing sum.`.\n","4. Crea una estructura condicional (fuera del manejo de excepciones) que determine si alguno de los argumentos no es par. En caso de que alguno no lo sea, eleva un error de valor que tenga como mensaje la frase `all values must be even`. "]},{"cell_type":"code","execution_count":null,"metadata":{"id":"UBB4hka67ZkB"},"outputs":[],"source":["# Write your code below:\n","\n"]},{"attachments":{},"cell_type":"markdown","metadata":{},"source":["# Navigation\n","\n","- **Previous lesson**: [Classes](./classes.ipynb)\n","- **Next lesson**: [Packages](./packages.ipynb)"]}],"metadata":{"colab":{"authorship_tag":"ABX9TyOqkdzlgvaxPWf/B3qgPJlZ","collapsed_sections":["s65z3Wt39b7W","fLWkiKzx9fTm","qzhCjBRBzRDa","-DKcF6q50gAp","pgjDQlN605j5","a0ISIYYt_iq3","neF9KusEw2Dy","PS8rpsCx7fyA","sacz-IDM7tmw","-Kkpfwh68bGA","lStQYj0E8mF3","3WT73f5s8xkQ","ZJ_C0uyA87XA","JGAZ-AUq915N","4uVom-gr-ZCA","g_qBK6LM-jqH","gYoN-W2N3shP","_GliAtBS5Zaq","MsOUWERC9NLm","qJ8rUYRN6NlC","l_-ET-iN89al","rR2ie8Ke7xwy","fcTmCxzH834B","Biie78Sq_EbJ","Hunm3Sma_rbd","jchnU4E2QvQS","fgJ-M-EiRg9q","xxNSgsRaR_SC","0B4SwWJXUl7N","lCHmecQ5VJCV","KHXI_Od6UcN5","5QpkFs3xbS2Z","QjjeOOf8d96B"],"provenance":[{"file_id":"1jH2xcSVbi6rEtypaoTc0huKAgzPFuln1","timestamp":1666127789028}]},"kernelspec":{"display_name":".venv","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.8.10"},"vscode":{"interpreter":{"hash":"edb3f8401898146638121a13b0247bbb0e9c0cce851d580080f4cb1d49fc2b60"}}},"nbformat":4,"nbformat_minor":0}
